# ==========================
# Wasmer.toml for Yielziey VXSite
# PHP 8.3 compatible
# ==========================

# General package info
[package]
name = "yielziey/vxsite"
version = "0.2.0"
description = "My Vexillum website project"

# Filesystem mapping
# Maps all project files (.) to /app in the container
[fs]
"/app" = "."

# Command to run the application
[[command]]
name = "start"
# Use PHP 8.3
module = "wasmer/php@8.3"
runner = "https://webc.org/runner/wasi"
# Start PHP built-in server with custom router.php
args = ["php", "-S", "0.0.0.0:8080", "-t", "/app", "/app/router.php"]

# Environment variables / secrets
[env]
# Database credentials
DB_HOST = { from = "secret" }
DB_NAME = { from = "secret" }
DB_USERNAME = { from = "secret" }
DB_PASSWORD = { from = "secret" }
DB_PORT = { from = "secret" }

# Email (PHPMailer)
SMTP_USER = { from = "secret" }
SMTP_PASS = { from = "secret" }

# Twitch API
TWITCH_CLIENT_ID = { from = "secret" }
TWITCH_CLIENT_SECRET = { from = "secret" }

# Spotify API
SPOTIFY_CLIENT_ID = { from = "secret" }
SPOTIFY_CLIENT_SECRET = { from = "secret" }
