# Final na wasmer.toml para sa vxsite

[package]
name = "yielziey/vxsite"
version = "0.2.2"
description = "My Vexillum website project"

[fs]
"/app" = "."

[[command]]
name = "start"
module = "wasmer/php"       # Official Wasmer PHP package
runner = "https://webc.org/runner/wasi"
args = [ "php", "-S", "0.0.0.0:8080", "-t", "/app", "/app/router.php" ]

[env]
# Database
DB_HOST = { from = "secret" }
DB_NAME = { from = "secret" }
DB_USERNAME = { from = "secret" }
DB_PASSWORD = { from = "secret" }
DB_PORT = { from = "secret" }

# Email (PHPMailer)
SMTP_USER = { from = "secret" }
SMTP_PASS = { from = "secret" }

# Twitch API
TWITCH_CLIENT_ID = { from = "secret" }
TWITCH_CLIENT_SECRET = { from = "secret" }

# Spotify API
SPOTIFY_CLIENT_ID = { from = "secret" }
SPOTIFY_CLIENT_SECRET = { from = "secret" }
