# ===============================
# WASMER TOML CONFIGURATION FILE
# ===============================

# 1️⃣ Package Info
[package]
name = "yielziey/vxsite"       # Pangalan ng iyong Wasmer package
version = "0.2.1"             # Version ng package, dapat match sa YAML kung ginagamit
description = "My Vexillum website project"

# 2️⃣ File System Mapping
# Lahat ng files sa local folder (.) ay mapupunta sa /app sa Wasmer container
[fs]
"/app" = "."

# 3️⃣ Command to Start App
[[command]]
name = "start"
# PHP 8.3 module
module = "wasmer/php@8.3"        
runner = "https://webc.org/runner/wasi"
# Utos para patakbuhin ang built-in PHP server at gumamit ng router.php
args = ["php", "-S", "0.0.0.0:8080", "-t", "/app", "/app/router.php"]

# 4️⃣ Environment Variables (Secrets)
# Siguraduhing lahat ng 'from = "secret"' ay may value sa Wasmer Secrets panel
[env]
# Database
DB_HOST = { from = "secret" }
DB_NAME = { from = "secret" }
DB_USERNAME = { from = "secret" }
DB_PASSWORD = { from = "secret" }
DB_PORT = { from = "secret" }

# PHPMailer / Email
SMTP_USER = { from = "secret" }
SMTP_PASS = { from = "secret" }

# Twitch API
TWITCH_CLIENT_ID = { from = "secret" }
TWITCH_CLIENT_SECRET = { from = "secret" }

# Spotify API
SPOTIFY_CLIENT_ID = { from = "secret" }
SPOTIFY_CLIENT_SECRET = { from = "secret" }
