# Pangkalahatang impormasyon tungkol sa iyong package
[package]
name = "yielziey/vxsite"
version = "0.2.1"
description = "My Vexillum website project"

# Pagma-map ng iyong mga files
# Ilalagay lahat ng files sa /app/ directory sa loob ng server
[fs]
"/app" = "."

# Command para patakbuhin ang application
[[command]]
name = "start"
# Gumagamit ng specific PHP 8.3 runtime
module = "wasmer/php@8.3"
runner = "https://webc.org/runner/wasi"
# Utos para simulan ang PHP built-in web server at gamitin ang router.php
args = ["php", "-S", "0.0.0.0:8080", "-t", "/app", "/app/router.php"]

# Secrets na kailangan ng website
[env]
# Database
DB_HOST = { from = "secret" }
DB_NAME = { from = "secret" }
DB_USERNAME = { from = "secret" }
DB_PASSWORD = { from = "secret" }
DB_PORT = { from = "secret" }

# Email (PHPMailer)
SMTP_USER = { from = "secret" }
SMTP_PASS = { from = "secret" }

# Twitch API
TWITCH_CLIENT_ID = { from = "secret" }
TWITCH_CLIENT_SECRET = { from = "secret" }

# Spotify API
SPOTIFY_CLIENT_ID = { from = "secret" }
SPOTIFY_CLIENT_SECRET = { from = "secret" }
